### ISSUE TITLE
getting some strange errors in the last hour

### ISSUE THREAD

**Issue by balupton** [juliangruber/ci-watch#3]
```
balupton@balbook ~/P/d/e/p/coffeekup> ci-watch

Build #26 docpad/docpad-plugin-coffeekup #v2.4.0
https://travis-ci.org/docpad/docpad-plugin-coffeekup/builds/222812174

  ⠴ node_js: 0.8 
  ⠴ node_js: 0.10 
  ⠴ node_js: 0.12 
  ⠴ node_js: 4 
  ⠴ node_js: 6 
  ⠴ node_js: 7 


events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND api.travis-ci.org api.travis-ci.org:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
```

```
balupton@balbook ~/P/d/e/p/coffeekup> ci-watch
⠧ Loading build

events.js:163
      throw er; // Unhandled 'error' event
      ^
HTTPError
    at stream.catch.then.data (/Users/balupton/.nvm/versions/node/v7.9.0/lib/node_modules/ci-watch/node_modules/got/index.js:123:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

not sure what they mean or what their cause and fix are

build it is trying to get is https://travis-ci.org/docpad/docpad-plugin-coffeekup/builds/222812174 which currently looks like

<img width="977" alt="screen shot 2017-04-17 at 10 56 16 pm" src="https://cloud.githubusercontent.com/assets/61148/25092625/1e4fa8c6-23c1-11e7-9d2d-cbb50c8bb048.png">

**Comment by balupton** [comment]
happening on another as well:

```
balupton@balbook ~/P/d/e/p/cleanurls> ci-watch
⠇ Loading build

events.js:163
      throw er; // Unhandled 'error' event
      ^
HTTPError
    at stream.catch.then.data (/Users/balupton/.nvm/versions/node/v7.9.0/lib/node_modules/ci-watch/node_modules/got/index.js:123:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
balupton@balbook ~/P/d/e/p/cleanurls> ci-watch
⠧ Loading build

events.js:163
      throw er; // Unhandled 'error' event
      ^
HTTPError
    at stream.catch.then.data (/Users/balupton/.nvm/versions/node/v7.9.0/lib/node_modules/ci-watch/node_modules/got/index.js:123:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by juliangruber** [comment]
ok, first: we should make the error messages more meaningful. then, i guess more rate limiting or using the pushing travis api endpoints instead of polling
