### ISSUE TITLE
ci-watch stopped worked

### ISSUE THREAD

**Issue by mafintosh** [juliangruber/ci-watch#6]
Everytime i use ci-watch it stopped working (which is unfortunate cause it is soooooo useful). Here is an example error

```
> ci-watch
⠋ Loading build
events.js:173
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. (<!DOCTYPE html>
	<html>
	  <head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta charset="utf-8">
		<title>Application Error</title>
		<style media="screen">
		  html,body,iframe {
			margin: 0;
			padding: 0;
		  }
		  html,body {
			height: 100%;
			overflow: hidden;
		  }
		  iframe {
			width: 100%;
			height: 100%;
			border: 0;
		  }
		</style>
	  </head>
	  <body>
		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
	  </body>
	</html>)
    at Watch.emit (events.js:171:17)
    at _getBuild.err (/usr/local/lib/node_modules/ci-watch/node_modules/travis-watch/index.js:115:26)
    at _getBuilds (/usr/local/lib/node_modules/ci-watch/node_modules/travis-watch/index.js:62:21)
    at /usr/local/lib/node_modules/ci-watch/node_modules/travis-ci/lib/travis-ci.js:51:21
    at Request._callback (/usr/local/lib/node_modules/ci-watch/node_modules/travis-ci/lib/travis-http.js:49:13)
    at Request.self.callback (/usr/local/lib/node_modules/ci-watch/node_modules/request/request.js:187:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/usr/local/lib/node_modules/ci-watch/node_modules/request/request.js:1044:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/ci-watch/node_modules/request/request.js:965:12)

```

**Comment by juliangruber** [comment]
can you give me a repo to repro? i tested with one and it still worked

**Comment by mafintosh** [comment]
that one was utp-native (on linux if that matters), latest node 9
